banners/config/routes.rb
TestAdv::Application.routes.draw do
  resources :banner_for_platforms do
    post :click, on: :member
  end

  resources :banners

  resources :platforms do
    get :view, on: :member
  end

  root :to => 'platforms#index'

end

banners/app/models/banner.rb
class Banner < ActiveRecord::Base
  has_many :platforms, through: :banner_for_platforms
  has_many :banner_for_platforms, dependent: :destroy
  attr_accessible :image, :name
  mount_uploader :image, ImageUploader
end

banners/app/models/banner_for_platform.rb
class BannerForPlatform < ActiveRecord::Base
  belongs_to :banner
  belongs_to :platform
  attr_accessible :amount_clicks, :amount_views, :default, :max_views, :banner_id, :platform_id
end

banners/app/models/platform.rb
class Platform < ActiveRecord::Base
  has_many :banners, through: :banner_for_platforms
  has_many :banner_for_platforms, dependent: :destroy
  attr_accessible :name
end

banners/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

banners/app/controllers/banner_for_platforms_controller.rb
class BannerForPlatformsController < ApplicationController
  def click
    @bfp = BannerForPlatform.find(params[:id])
    @bfp.amount_clicks += 1
    @bfp.save
    render :nothing => true
  end

  # GET /banner_for_platforms
  # GET /banner_for_platforms.json
  def index
    @banner_for_platforms = BannerForPlatform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banner_for_platforms }
    end
  end

  # GET /banner_for_platforms/1
  # GET /banner_for_platforms/1.json
  def show
    @banner_for_platform = BannerForPlatform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner_for_platform }
    end
  end

  # GET /banner_for_platforms/new
  # GET /banner_for_platforms/new.json
  def new
    @banner_for_platform = BannerForPlatform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner_for_platform }
    end
  end

  # GET /banner_for_platforms/1/edit
  def edit
    @banner_for_platform = BannerForPlatform.find(params[:id])
  end

  # POST /banner_for_platforms
  # POST /banner_for_platforms.json
  def create
    @banner_for_platform = BannerForPlatform.new(params[:banner_for_platform])

    respond_to do |format|
      if @banner_for_platform.save
        format.html { redirect_to @banner_for_platform, notice: 'Banner for platform was successfully created.' }
        format.json { render json: @banner_for_platform, status: :created, location: @banner_for_platform }
      else
        format.html { render action: "new" }
        format.json { render json: @banner_for_platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banner_for_platforms/1
  # PUT /banner_for_platforms/1.json
  def update
    @banner_for_platform = BannerForPlatform.find(params[:id])

    respond_to do |format|
      if @banner_for_platform.update_attributes(params[:banner_for_platform])
        format.html { redirect_to @banner_for_platform, notice: 'Banner for platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner_for_platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banner_for_platforms/1
  # DELETE /banner_for_platforms/1.json
  def destroy
    @banner_for_platform = BannerForPlatform.find(params[:id])
    @banner_for_platform.destroy

    respond_to do |format|
      format.html { redirect_to banner_for_platforms_url }
      format.json { head :no_content }
    end
  end
end

banners/app/controllers/banners_controller.rb
class BannersController < ApplicationController
  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/new
  # GET /banners/new.json
  def new
    @banner = Banner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/1/edit
  def edit
    @banner = Banner.find(params[:id])
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banners/1
  # PUT /banners/1.json
  def update
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :no_content }
    end
  end
end

banners/app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController

  def view
    @banner_for_platform = BannerForPlatform.includes(:banner).where(:platform_id => params[:id], :default => false)    
      .where('amount_views = (SELECT MIN(amount_views) from banner_for_platforms WHERE platform_id = ? AND "default" = ? AND amount_views < max_views)', 2, false)
      .where('amount_views < max_views').first
    @banner_for_platform = BannerForPlatform.where(:default => true, :platform_id => params[:id]).first if @banner_for_platform.blank?
    @banner_for_platform.amount_views += 1
    @banner_for_platform.save
  end
  # GET /platforms
  # GET /platforms.json
  def index
    @platforms = Platform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @platforms }
    end
  end

  # GET /platforms/1
  # GET /platforms/1.json
  def show
    @platform = Platform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/new
  # GET /platforms/new.json
  def new
    @platform = Platform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @platform }
    end
  end

  # GET /platforms/1/edit
  def edit
    @platform = Platform.find(params[:id])
  end

  # POST /platforms
  # POST /platforms.json
  def create
    banners = Banner.where(:id => params[:platform].delete(:banners))
    @platform = Platform.new(params[:platform])
    @platform.banners = banners

    respond_to do |format|
      if @platform.save
        format.html { redirect_to @platform, notice: 'Platform was successfully created.' }
        format.json { render json: @platform, status: :created, location: @platform }
      else
        format.html { render action: "new" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /platforms/1
  # PUT /platforms/1.json
  def update
    @platform = Platform.find(params[:id])
    banners = Banner.where(:id => params[:platform].delete(:banners))
    @platform.banners = banners

    respond_to do |format|
      if @platform.update_attributes(params[:platform])
        format.html { redirect_to @platform, notice: 'Platform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1
  # DELETE /platforms/1.json
  def destroy
    @platform = Platform.find(params[:id])
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to platforms_url }
      format.json { head :no_content }
    end
  end
end

banners/app/helpers/application_helper.rb
module ApplicationHelper
end

banners/app/helpers/banner_for_platforms_helper.rb
module BannerForPlatformsHelper
end

banners/app/helpers/banners_helper.rb
module BannersHelper
end

banners/app/helpers/platforms_helper.rb
module PlatformsHelper
end

banners/app/views/banner_for_platforms/_form.html.haml
= form_for @banner_for_platform, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :banner_id, :class => 'control-label'
    .controls
      = f.collection_select(:banner_id, Banner.all, :id, :name)
  .control-group
    = f.label :platform_id, :class => 'control-label'
    .controls
      = f.collection_select(:platform_id, Platform.all, :id, :name)
  .control-group
    = f.label :max_views, :class => 'control-label'
    .controls
      = f.number_field :max_views, :class => 'number_field'
  .control-group
    = f.label :amount_views, :class => 'control-label'
    .controls
      = f.number_field :amount_views, :class => 'number_field'
  .control-group
    = f.label :amount_clicks, :class => 'control-label'
    .controls
      = f.number_field :amount_clicks, :class => 'number_field'
  .control-group
    = f.label :default, :class => 'control-label'
    .controls
      = f.check_box :default, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), banner_for_platforms_path, :class => 'btn'                   

banners/app/views/banner_for_platforms/edit.html.haml
- model_class = BannerForPlatform
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/banner_for_platforms/index.html.haml
- model_class = BannerForPlatform
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:banner_id)
      %th= model_class.human_attribute_name(:platform_id)
      %th= model_class.human_attribute_name(:max_views)
      %th= model_class.human_attribute_name(:amount_views)
      %th= model_class.human_attribute_name(:amount_clicks)
      %th= model_class.human_attribute_name(:default)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @banner_for_platforms.each do |banner_for_platform|
      %tr
        %td= link_to banner_for_platform.id, banner_for_platform_path(banner_for_platform)
        %td
          = link_to banner_path(banner_for_platform.banner) do
            = image_tag banner_for_platform.banner.image rescue nil
        %td= link_to banner_for_platform.platform.name, platform_path(banner_for_platform.platform)
        %td= banner_for_platform.max_views
        %td= banner_for_platform.amount_views
        %td= banner_for_platform.amount_clicks
        %td= banner_for_platform.default
        %td= l banner_for_platform.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_banner_for_platform_path(banner_for_platform), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), banner_for_platform_path(banner_for_platform), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
  = link_to t('.new', :default => t("helpers.links.new")), new_banner_for_platform_path, :class => 'btn btn-primary'                           

banners/app/views/banner_for_platforms/new.html.haml
- model_class = BannerForPlatform
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/banner_for_platforms/show.html.haml
- model_class = BannerForPlatform
.page-header
  %h1= t '.title', :default => model_class.model_name.human
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:banner_id)
      \:
  %dd= @banner_for_platform.banner.name
  %dt
    %strong
      = model_class.human_attribute_name(:platform_id)
      \:
  %dd= @banner_for_platform.platform.name
  %dt
    %strong
      = model_class.human_attribute_name(:max_views)
      \:
  %dd= @banner_for_platform.max_views
  %dt
    %strong
      = model_class.human_attribute_name(:amount_views)
      \:
  %dd= @banner_for_platform.amount_views
  %dt
    %strong
      = model_class.human_attribute_name(:amount_clicks)
      \:
  %dd= @banner_for_platform.amount_clicks
  %dt
    %strong
      = model_class.human_attribute_name(:default)
      \:
  %dd= @banner_for_platform.default
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    banner_for_platforms_path, :class => 'btn'               |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")),             |
    edit_banner_for_platform_path(@banner_for_platform), :class => 'btn' |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    banner_for_platform_path(@banner_for_platform),                                                              |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |

banners/app/views/banners/_form.html.haml
= form_for @banner, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :image, :class => 'control-label'    
    .controls
      = f.file_field :image, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      banners_path, :class => 'btn'                                |

banners/app/views/banners/edit.html.haml
- model_class = Banner
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/banners/index.html.haml
- model_class = Banner
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th Platforms
      %th= model_class.human_attribute_name(:image)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @banners.each do |banner|
      %tr
        %td= link_to banner.id, banner_path(banner)
        %td= banner.name
        %td 
          = banner.platforms.present? ? '|' : 'nothing'
          - banner.platforms.each do |platform|
            =link_to platform.name, platform_path(platform)
            |
        %td= image_tag banner.image rescue nil
        %td= banner.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_banner_path(banner), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), banner_path(banner), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'                                                                          
  = link_to t('.new', :default => t("helpers.links.new")), new_banner_path, :class => 'btn btn-primary'                            

banners/app/views/banners/new.html.haml
- model_class = Banner
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/banners/show.html.haml
- model_class = Banner
.page-header
  %h1= t '.title', :default => model_class.model_name.human
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @banner.name
  %dt
    %strong
      Platforms:
  %dd
    = @banner.platforms.present? ? '|' : 'nothing'
    - @banner.platforms.each do |platform|
      =link_to platform.name, platform_path(platform)
      |
  %dt
    %strong
      = model_class.human_attribute_name(:image)
      \:
  %dd= image_tag @banner.image rescue nil
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), banners_path, :class => 'btn'                            
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_banner_path(@banner), :class => 'btn' 
  = link_to t('.destroy', :default => t("helpers.links.destroy")), banner_path(@banner), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'                                                                                   

banners/app/views/common/_navigation.html.haml
.widget-title
  %ul.nav.nav-tabs
    %li{class: "#{'active' if params[:controller] == 'platforms' }"}
      = link_to "Platforms", platforms_path
    %li{class: "#{'active' if params[:controller] == 'banner_for_platforms'}" }
      = link_to "Banner for platforms", banner_for_platforms_path
    %li{class: "#{'active' if params[:controller] == 'banners'}" }
      = link_to "Banners", banners_path

banners/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TestAdv
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #main-content
      .widget-box
        = render 'common/navigation' 
        #bills_content.widget-content.tab-content
          .tab-pane.active
            #content
              = yield
        

banners/app/views/platforms/_form.html.haml
= form_for @platform, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :banners, :class => 'control-label'
    .controls
      = f.collection_select(:banners, Banner.all, :id, :name, {:selected => @platform.banner_ids},{:multiple => true})

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), platforms_path, :class => 'btn'

banners/app/views/platforms/edit.html.haml
- model_class = Platform
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/platforms/index.html.haml
- model_class = Platform
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th Banners
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @platforms.each do |platform|
      %tr
        %td= link_to platform.id, platform_path(platform)
        %td= platform.name
        %td 
          = platform.banners.present? ? '|' : 'nothing'
          - platform.banners.each do |banner|
            =link_to banner.name, banner_path(banner)
            |
        %td= l platform.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_platform_path(platform), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), platform_path(platform), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'  
          = link_to 'view platform', view_platform_path(platform), :class => 'btn btn-mini btn-warning'
  = link_to t('.new', :default => t("helpers.links.new")), new_platform_path, :class => 'btn btn-primary'                            

banners/app/views/platforms/new.html.haml
- model_class = Platform
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => 'form'

banners/app/views/platforms/show.html.haml
- model_class = Platform
.page-header
  %h1= t '.title', :default => model_class.model_name.human
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @platform.name
  %dt
    %strong Banners:
  %dd
    = @platform.banners.present? ? '|' : 'nothing'
    - @platform.banners.each do |banner|
      =link_to banner.name, banner_path(banner)
      |
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), platforms_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_platform_path(@platform), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), platform_path(@platform), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

banners/app/views/platforms/view.html.haml
.span12
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cu
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
.span3
  #banner_container{bfp_id: @banner_for_platform.id}
    %h3 banner
    =image_tag @banner_for_platform.banner.image    