tickets/config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  resources :tickets, only: [:new, :create, :show, :index, :update] do
    resources :comments, shallow: true
  end

  root 'tickets#index'

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
end

tickets/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket

  validates :ticket_id, :body, presence: true
end

tickets/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include ActiveModel::Transitions

  DEPARTMENTS = ['payments', 'technical_issues', 'other']
  SELECT_DEPARTMENTS = DEPARTMENTS.map { |s| [s.capitalize, s] }

  belongs_to :user
  has_many :comments

  validates :name, presence: true
  validates :email, presence: true
  validates :department, presence: true, :inclusion => { :in => DEPARTMENTS }
  validates :subject, presence: true
  validates :description, presence: true
  validates :uref, presence: true, uniqueness: true

  before_validation :set_uref, on: :create

  scope :fresh, -> { where(user_id: nil, state: 'waiting_for_staff_response') }
  scope :in_process, -> { where.not(user_id: nil).where(state: %w(waiting_for_staff_response waiting_for_customer on_hold)) }
  scope :done, -> { where(state: %w(cancelled completed)) }

  state_machine auto_scopes: true do
    state :waiting_for_staff_response
    state :waiting_for_customer
    state :on_hold
    state :cancelled
    state :completed

    event :cancel do
      transitions :to => :cancelled, :from => [:waiting_for_staff_response, :waiting_for_customer, :on_hold]
    end

    event :complete do
      transitions :to => :completed, :from => [:waiting_for_staff_response, :waiting_for_customer, :on_hold]
    end

    event :hold do
      transitions :to => :on_hold, :from => [:waiting_for_staff_response, :waiting_for_customer]
    end

    event :to_customer do
      transitions :to => :waiting_for_customer, :from => [:waiting_for_staff_response]
    end

    event :to_staff do
      transitions :to => :waiting_for_staff_response, :from => [:on_hold, :waiting_for_customer]
    end
  end

  def self.valid_uref? uref
    (/\A[A-Z]{3}-[0-9A-F]{2}-[A-Z]{3}-[0-9A-F]{2}-[A-Z]{3}\z/ =~ uref).present?
  end

  def set_uref
    self.uref = "#{rand_string 3}-#{rand_hex 2}-#{rand_string 3}-#{rand_hex 2}-#{rand_string 3}"
  end

  def rand_string size, library = ('A'..'Z').to_a
    ([nil] * size).map {|x| library.sample }.join
  end

  def rand_hex size
    hex_library = [*'0'..'9', *'A'..'F']
    rand_string size, hex_library
  end
end

tickets/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :tickets
  has_many :comments

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  def to_s
    name
  end
end

tickets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  private

  def not_authenticated
    redirect_to new_ticket_path
  end
end

tickets/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]
  before_action :set_ticket, only: :create

  def new
    @comment = Comment.new
  end

  def create
    @comment = @ticket.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      # CommentMailer.comment_created(@comment).deliver_later
      redirect_to(ticket_path(id: @ticket.uref), notice: 'Comment was successfully created.')
    else
      render 'tickets/show'
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

tickets/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create, :update, :show]
  before_action :set_ticket, only: [:update]

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      TicketMailer.ticket_created(@ticket).deliver_later
      redirect_to({ action: :new }, notice: 'Ticket was successfully created.')
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      @ticket.send("#{params[:event]}!") if params[:event].present?
      redirect_to ticket_path(id: @ticket.uref), notice: 'Ticket was successfully updated.'
    else
      render :show
    end
  end

  def show
    @ticket = Ticket.find_by(uref: params[:id])

    redirect_to({ action: :new }, alert: "Ticket ##{params[:id]} doesn't exist.") and return unless @ticket
  end

  def index
    @tickets_fresh = Ticket.fresh
    @tickets_in_process = Ticket.in_process
    @tickets_done = Ticket.done
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :email, :department, :subject, :description, :user_id)
  end
end

tickets/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(tickets_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:login, notice: 'Logged out!')
  end
end

tickets/app/helpers/application_helper.rb
module ApplicationHelper
  def login_page
    controller_name == 'user_sessions' && action_name == 'new'
  end

  def label_for_ticket ticket
    {
      waiting_for_staff_response: ticket.user_id ? 'warning' : 'info',
      waiting_for_customer: 'warning',
      on_hold: 'warning',
      cancelled: 'danger',
      completed: 'success'
    }[ticket.current_state]
  end
end

tickets/app/views/comments/_comment.slim
- user_name = comment.user || 'Guest'
- classes = user_name == 'Guest' ? 'col-md-9' : 'col-md-9 col-md-offset-3'
.comment class="no-padding panel panel-success #{classes}"
  .panel-heading
    = user_name
  .panel-body
    = comment.body

tickets/app/views/layouts/application.slim
doctype html
html lang='en'
  head
    meta content='text/html; charset=utf-8' http-equiv='Content-Type'

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container-fluid
      .row
        .col-md-12
          .nav.pull-left
            = link_to 'Dashboard', tickets_path, class: 'btn btn-primary padding-top-md'
          .nav.pull-right
            - if current_user
              = link_to "Logout", :logout, method: :post, class: 'btn btn-danger padding-top-md', role: 'button'
            - else
              = link_to "Login", :login, class: 'btn btn-info padding-top-md', role: 'button' unless login_page
      .row
        .col-md-10.col-md-offset-1.notices
          = bootstrap_flash
    .container-fluid
      .row
        .col-md-10.col-md-offset-1
          = yield

tickets/app/views/shared/_errors.slim
- if object.errors.any?
  .alert.alert-danger
    a.close data-dismiss="alert" &#215;
    ul
      - object.errors.full_messages.each do |msg|
        = content_tag :li, msg, :id => "error_#{msg}" if msg.is_a?(String)

tickets/app/views/tickets/_ticket_preview.slim
.ticket-preview.well
  table.table.no-border
    tr
      td= ticket.name
      td
        .pull-right.text-info = ticket.department.humanize
  p
    strong= ticket.subject
  p.small= link_to truncate(ticket.description, length: 100), ticket_path(id: ticket.uref)
  table.table.no-border
    tr
      td width='50%'
        - if ticket.user
          .small
            | Assignee:
            span.text-info= " #{ticket.user}"
      td
        .pull-right= tag_label(ticket.state.humanize.downcase, label_for_ticket(ticket))

    tr colspan=2
      td
        - if ticket.comments.present?
          = "Comments: #{ticket.comments.count}"

tickets/app/views/tickets/index.slim
.container-fluid
  .row
    .col-md-4.tickets_column
      h4.text-center new
      = render partial: 'tickets/ticket_preview', collection: @tickets_fresh, as: :ticket
    .col-md-4.tickets_column
      h4.text-center in process
      = render partial: 'tickets/ticket_preview', collection: @tickets_in_process, as: :ticket
    .col-md-4.tickets_column
      h4.text-center done
      = render partial: 'tickets/ticket_preview', collection: @tickets_done, as: :ticket

tickets/app/views/tickets/new.slim
.container-fluid
  .row
    .col-md-12
      .new-ticket
        .page-header
          h1 New Ticket

        = render 'shared/errors', object: @ticket

        = form_for @ticket, html: { class: 'form-horizontal' } do |f|
          .form-group
            = f.label :name, nil, class: 'control-label col-md-2'
            .col-md-4
              = f.text_field :name, class: 'form-control', placeholder: 'Name', required: true

          .form-group
            = f.label :email, nil, class: 'control-label col-md-2'
            .col-md-4
              = f.text_field :email, class: 'form-control', placeholder: 'Email', required: true

          .form-group
            = f.label :department, nil, class: 'control-label col-md-2'
            .col-md-4
              = f.select :department, options_for_select(Ticket::SELECT_DEPARTMENTS), { prompt: "Choose Department..." }, class: 'form-control', required: true

          .form-group
            = f.label :subject, nil, class: 'control-label col-md-2'
            .col-md-4
              = f.text_field :subject, class: 'form-control', placeholder: 'What is your problem about', required: true

          .form-group
            = f.label :description, nil, class: 'control-label col-md-2'
            .col-md-6
              = f.text_area :description, class: 'form-control', placeholder: 'Describe your problem', required: true, rows: 6

          .form-group
            .col-md-offset-2.col-md-4
              = f.submit 'Create', class: 'btn btn-success'

tickets/app/views/tickets/show.slim
.ticket
  .page-header
    h2 Ticket ##{@ticket.uref}

  = render 'shared/errors', object: @ticket

  = form_for @ticket, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label 'State', nil, class: 'control-label col-md-2'
      .col-md-4 style='padding-top: 5px;'
        = tag_label(@ticket.state.humanize.downcase, label_for_ticket(@ticket))

    .form-group
      = f.label 'Action', nil, class: 'control-label col-md-2'
      .col-md-4
        = select_tag :event, options_for_select(@ticket.available_transitions), prompt: 'Nothing', class: 'form-control', disabled: current_user.blank?

    .form-group
      = f.label 'Assignee', nil, class: 'control-label col-md-2'
      .col-md-4
        = f.select :user_id, options_from_collection_for_select(User.all, :id, :name, @ticket.user_id), { prompt: "Choose Assignee..." }, class: 'form-control', required: true, disabled: current_user.blank?

    .form-group
      = f.label :department, nil, class: 'control-label col-md-2'
      .col-md-4
        = f.select :department, options_for_select(Ticket::SELECT_DEPARTMENTS), { prompt: "Choose Department..." }, class: 'form-control', required: true, disabled: current_user.blank?

    .form-group
      = f.label :name, nil, class: 'control-label col-md-2'
      .col-md-4
        = f.text_field :name, class: 'form-control', placeholder: 'Name', disabled: true

    .form-group
      = f.label :email, nil, class: 'control-label col-md-2'
      .col-md-4
        = f.text_field :email, class: 'form-control', placeholder: 'Email', disabled: true

    .form-group
      = f.label :subject, nil, class: 'control-label col-md-2'
      .col-md-4
        = f.text_field :subject, class: 'form-control', placeholder: 'What is your problem about', disabled: true

    .form-group
      = f.label :description, nil, class: 'control-label col-md-2'
      .col-md-6
        = f.text_area :description, class: 'form-control', placeholder: 'Describe your problem', disabled: true, rows: 6
    - if current_user.present?
      .form-group
        .col-md-offset-2.col-md-4
          = f.submit nil, class: 'btn btn-success'

  .comments
    - @comment ||= Comment.new
    = render 'shared/errors', object: @comment
    .new-comment.col-md-8.col-md-offset-2.no-padding
      = form_for [@ticket, @comment] do |f|
        .form-group
          = f.hidden_field :user_id
          = f.text_area :body, class: 'form-control'
        .form-group
          = f.submit nil, class: 'btn btn-success'
    .comments-list.col-md-10.com-md-offset-1
      = render partial: 'comments/comment', collection: @ticket.comments

tickets/app/views/user_sessions/new.slim
.container-fluid
  .row
    .col-md-12
      .login-container.center-block
        .page-header
          h1
            | Login
            small.left-buffer-med for staff only

        = form_tag user_sessions_path, method: :post do |_|
          .form-group
            = label_tag :email
            = text_field_tag :email, nil, class: 'form-control'

          .form-group
            = label_tag :password
            = password_field_tag :password, nil, class: 'form-control'

          = submit_tag 'Login', class: 'btn btn-success'